Tests, README.md and utilities
mvvmvvmvv/Sprint_3 pull request #1
Opened 2023-06-04 15:39 UTC by mvvmvvmvv

2023-06-04 18:25 UTC, kadirovgm requested changes

2023-06-04 18:25 UTC, kadirovgm commented on Locators.py
> +class Locators:
- Можно лучше: класс с локаторами лучше разделить на несколько: например `AuthPageLocators`, `MainPageLocators`
Сейчас это не критично, но в будущем это точно стоит сделать, так как таким образом ты не будешь импортить лишние локаторы в файл с тестами на экран авторизации. Т.е. у каждой страницы должен быть свой класс с локаторами.
    
    При таком подходе код станет лаконичнее, легко поддерживаемой. Ведь у экрана авторизации и у экрана главной могут быть свои NEXT_BUTTON например. Тогда можно будет легко оба обозвать именно так:
    `MainPageLocators.NEXT_BUTTON` и `AuthPageLocators.NEXT_BUTTON`

2023-06-04 18:25 UTC, kadirovgm commented on Locators.py
> +    BUNS_ENABLED = \
Нужно исправить: локаторы типа такого (длинные, громоздкие, и завязанные на большом количестве нестабильных аттрибутах элемента) часто нестабильны и падают при малейшем изменении кода фронтенда. Поэтому, пожалуйста, перечитай раздел нашего курса про локаторы, и напиши более стабильные и короткие локаторы

2023-06-04 18:25 UTC, kadirovgm commented on conftest.py
> +    yield browser
Отлично!

2023-06-04 18:25 UTC, kadirovgm commented on tests/test_login_page.py
> +        driver = webdriver.Chrome()
Нужно исправить: ты ведь уже делал эти шаги в фикстуре driver - кажется нет необходимости здесь снова их повтроять, так что кажется эти строки лишние

2023-06-04 18:25 UTC, kadirovgm commented on tests/test_login_page.py
> +                                                                         Locators.LOG_IN))).click()
нужно исправить: у тебя же есть фикстура login - почему бы не воспользоваться им? не стоит повторять одинаковый код, если есть возможность переиспользовать, лучше переиспользовать. Это будет удобнее для масштабирования проекта, и легче в поддержке

2023-06-04 18:25 UTC, kadirovgm commented on tests/test_login_page.py
> +        driver.find_element(By.XPATH, Locators.INPUT_EMAIL_ON_LOGIN).send_keys(test_email)
Нужно исправить: фикстура login

2023-06-04 18:25 UTC, kadirovgm commented on tests/test_login_page.py
> +        driver = webdriver.Chrome()
нужно исправить: ты это уже делал в фикстуре driver

2023-06-04 18:25 UTC, kadirovgm commented on tests/test_login_page.py
> +        driver = webdriver.Chrome()
нужно исправить: ты это уже делал в фикстуре driver

2023-06-04 18:25 UTC, kadirovgm commented on tests/test_login_page.py
> +        driver.find_element(By.XPATH, Locators.INPUT_EMAIL_ON_LOGIN).send_keys(test_email)
Нужно исправить: фикстура login

2023-06-04 18:25 UTC, kadirovgm commented on tests/test_main_page.py
> +        driver = webdriver.Chrome()
нужно исправить: ты это уже делал в фикстуре driver - твоя фикстура driver выполняется каждый раз перед каждым тестом, собственно это и есть его прямое назначение, ты не определил ему скоуп, а значит по дефолту на каждый тестовый метод. Также можно определить скоуп класса или сессии

2023-06-04 18:25 UTC, kadirovgm commented on tests/test_main_page.py
> +        driver = webdriver.Chrome()
нужно исправить: ты это уже делал в фикстуре driver

2023-06-04 18:25 UTC, kadirovgm commented on tests/test_main_page.py
> +        driver = webdriver.Chrome()
нужно исправить: ты это уже делал в фикстуре driver

2023-06-04 18:25 UTC, kadirovgm commented on tests/test_registration_page.py
> +        driver = webdriver.Chrome()
нужно исправить: ты это уже делал в фикстуре driver

2023-06-04 18:25 UTC, kadirovgm commented on tests/test_registration_page.py
> +        driver = webdriver.Chrome()
нужно исправить: ты это уже делал в фикстуре driver

2023-06-04 18:25 UTC, kadirovgm commented on tests/test_registration_page.py
> +        assert WebDriverWait(driver, 5).until(ec.visibility_of_element_located((By.XPATH,
Можно лучше: это точно гарантирует, что регистрация успешна?

2023-06-04 18:25 UTC, kadirovgm commented on tests/test_registration_page.py
> +        driver.find_element(By.XPATH, Locators.INPUT_NAME).send_keys(test_name)
Можно лучше: для регистрации можешь также написать фикстуру, по аналогии с login

2023-06-04 18:25 UTC, kadirovgm commented on tests/test_user_profile.py
> +        expected_text = "В этом разделе вы можете изменить свои персональные данные"
Можно лучше: тестовые статичные данные лучше выносить в отдельный файл типа [data.py](http://data.py/) или [urls.py](http://urls.py/)
Это нужно для легкой поддержке проекта и переиспользовании тестовых данных, мы должны стремиться к тому, чтобы разделять код и тестовые данные, тем самым избегая повторений.

2023-06-04 18:25 UTC, kadirovgm commented on tests/test_user_profile.py
> +        assert WebDriverWait(driver, 3).until(ec.visibility_of_element_located((By.XPATH, Locators.LOG_IN)))
Можно лучше: для удобной отладки ошибок можно дописывать в assert-ы assert messages

2023-06-12 10:42 UTC, mvvmvvmvv commented on tests/test_login_page.py
> +                                                                         Locators.LOG_IN))).click()
Фикстура login закрывает стандартный сценарий авторизации с домашней страницы, а эти кейсы довольно нестандартные и предварительно логиниться там как раз не надо. На мой взгляд этот метод надо реализовывать в рамках POM в классе страницы логина (и его же потом вызывать в фикстуре).

2023-06-12 20:12 UTC, kadirovgm approved these changes

2023-06-12 20:12 UTC, kadirovgm commented on tests/test_login_page.py
> +        # а в рамках POM в классе страницы LoginPage (в данном случае). Но мы это пока "не проходили"  :)
да, я тебя понял, ок)

2023-06-12 20:12 UTC, kadirovgm commented on urls.py
> +class Urls:
супер!

2023-06-12 21:07 UTC, merged